### ISSUE TITLE
Unable to find img

### ISSUE THREAD

**Issue by N4IRS** [inindev/odroid-m1#1]
I tried downloading the image from <wget https://github.com/inindev/odroid-m1/releases/download/v12.0/bookworm.img.xz>
This failed. Where can I find your image to try?

Thanks, Steve

**Comment by inindev** [comment]
Try it again, I just pushed up the image.  The url is: https://github.com/inindev/odroid-m1/releases/download/v12.0-rc1/bookworm_12.0-prerelease.img.xz

**Comment by N4IRS** [comment]
That worked. I'm looking forward to trying out your image. My plan is to try to use the M1 with Proxmox <https://github.com/pimox/pimox7>
