### ISSUE TITLE
Support request: kernel upgrade?

### ISSUE THREAD

**Issue by mkkot** [inindev/odroid-m1#13]
I'm a bit confused with the relation between uboot and kernel. I need to upgrade my kernel to backports:

```
The following NEW packages will be installed:
  linux-image-6.10.6+bpo-arm64
The following packages will be upgraded:
  linux-image-arm64
```

Otherwise my new wifi plug won't work: https://www.hardkernel.com/shop/wifi-module-5bk/
(apparently it's supported since kernel 6.2)

Will this work or it will cause a boot error?

Also, additional question, what if there is a Debian upgrade to next major version? Can I just run it as I do on x86 or I need to come back here for new image?

**Comment by inindev** [comment]
These are great questions.

Rockchip rk3568 devices such as the odroid m1 are well supported using the default Bookworm 6.1.x kernel. If for a particular reason you wish to run a more recent kernel, I recommend you add the following file which will auto-select the Trixie kernel:

**/etc/apt/preferences.d/99-trixie-kernel**
```
Package: *
Pin: release n=bookworm*
Pin-Priority: 600

Package: linux-image-arm64
Pin: release n=trixie
Pin-Priority: 800
```

The Trixie file sources need to be added to the end of the apt sources file:

**/etc/apt/sources.list**
```
# linux-image*
deb http://deb.debian.org/debian trixie main
#deb-src http://deb.debian.org/debian trixie main
```

Using this approach, all updates will automatically come using the standard ```sudo apt update``` and ```sudo apt upgrade``` process.

**Comment by mkkot** [comment]
```
uname -a
Linux nas9000 6.10.6+bpo-arm64 #1 SMP Debian 6.10.6-1~bpo12+1 (2024-08-26) aarch64 GNU/Linux
```

Works like a charm. I decided to go with backports this time. But my usb wireless card doesn't. Well, I will figure it out.
