### ISSUE TITLE
make_debian_img.sh can not find rk3568-odroid-m1.dtb

### ISSUE THREAD

**Issue by N4IRS** [inindev/odroid-m1#2]
Line 32 in the script is unable to find the .dtb
local dtb=$(download "$cache" 'https://github.com/inindev/odroid-m1/releases/download/v12.0/rk3568-odroid-m1.dtb')

**Comment by inindev** [comment]
thank you, I just fixed this, go ahead and do a ```git pull``` which should resolve it

**Comment by N4IRS** [comment]
That worked. I will also test the resulting image tonight.
