### ISSUE TITLE
No problem working report

### ISSUE THREAD

**Issue by N4IRS** [inindev/odroid-m1#3]
Just a quick note, I am running the image I built and a quick look says, things are good. I will test your published image when I get a chance. Nice!!!!

**Comment by N4IRS** [comment]
I am not able to see the NVME storage I have installed. fdisk -l only shows the SD card. Also found a few errors in the dmesg output. File attached
[Odroid_M1_Debian_dmesg.txt](https://github.com/inindev/odroid-m1/files/9155146/Odroid_M1_Debian_dmesg.txt)
.

**Comment by inindev** [comment]
Linux 6.1 should have resolved this issue.  Please test the latest release: https://github.com/inindev/odroid-m1/releases/tag/v12.0-rc2

**Comment by inindev** [comment]
confirmed m.2 ssd will boot from petitboot (no mmc needed)
