### ISSUE TITLE
Any plan to update odroid m1 to a newer u-boot ?

### ISSUE THREAD

**Issue by samuraikid0** [inindev/odroid-m1#8]
Is there any need or there are no big changes made on newer u-boot

Thanks !

**Comment by inindev** [comment]
I am wanting to update to pickup the debian 12.4 release but am waiting on u-boot v2024.01 to do so:

Release “v2024.01” is scheduled for 08 January 2024.
https://docs.u-boot.org/en/latest/develop/release_cycle.html

**Comment by samuraikid0** [comment]
Alright ! 
I'm currently using specifically your u-boot 
it's the only one that makes my bullseye system boot from nvme 

Thanks !

**Comment by samuraikid0** [comment]
All good with newer 2024.01 on M1

Thanks !

**Comment by inindev** [comment]
> All good with newer 2024.01 on M1
> 
> Thanks !

Did you try the u-boot build I did over here: https://github.com/inindev/uboot-rockchip/releases

I am in the process of putting together images and testing them.

**Comment by samuraikid0** [comment]
> > All good with newer 2024.01 on M1
> > Thanks !
> 
> Did you try the u-boot build I did over here: https://github.com/inindev/uboot-rockchip/releases
> 
> I am in the process of putting together images and testing them.

Yes I confirm M1 works well just flashed it 4h ago
